name: CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Install libguestfs-tools
        run: sudo apt-get install libguestfs-tools
      - name: Build ubuntu 20.04 rpi4 image with cloud-init config
        run: ./build.sh
      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-20.04.1-lava-master-arm64+raspi.img.xz
          path: out/*.img.xz
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        id: download_artifact
        uses: actions/download-artifact@v2
        with:
          name: ubuntu-20.04.1-lava-master-arm64+raspi.img.xz
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Get Release Version
        id: get_release_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ubuntu-20.04.1-lava-master-arm64+raspi.img.xz
          asset_name: ubuntu-20.04.1-lava-master-${{ steps.get_release_version.outputs.VERSION }}-arm64+raspi.img.xz
          asset_content_type: application/x-xz
      - name: Publish Release
        id: publish_release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
